#+title: README
#+author: Sidney Millen

The goal of this project is to provide for anyone the ability to construct a baseball database suitable for advanced analytics quickly, flexibly, and easily. This project is in an early stage of development and may contain bugs/errors.

* Disclaimers/notes
this project (at the time of writing) depends heavily on the pybaseball python library, which is not particularly well maintained these days. While I am considering either forking it and maintaining it myself, or switching some functions to the (slighly more maintained but still not as much as I'd hope) baseballr R library, I haven't gotten around to either of these options yet. Functionality may be limited until this situation is improved, either by myself or others. One particular point of weakness in pybaseball at the moment is the functions to pull from retrosheet, many of which will fail. I have implemented these functions myself for now, but again I am heavily considering just forking and updating pybaseball.

* Dependencies/Setup
The recommended way to set up this environment is to use [[https://devenv.sh/][Devenv]] or a nix shell to use the nix environment provided.

You may also install python with the pandas and pybaseball libraries, and sqlite


* Usage
The project is mainly a set of scripts that are intended to be run in a specific order. The general workflow will consist of using the scripts that pull data into csv files first, cleaning them if needed, and then generating the DB

** Configuration
⚠️ *You must copy config.example.py to config.py, or most scripts will not be able to run* ⚠️

This can be done either manually, or using setup.py. setup.py may be used for more in the future, but currently just copies the template config

After copying the example with either method, you are freely able to edit config.py to alter the behaviour of most of the scripts

More documentation will be added as this functionality is improved. right now you can configure a single year to pull all data from. The idea is that it is best to generate a separate database for each year, to allow users to create databases for several seasons and use the same SQL queries between databases with minimal change needed

** Data pulling scripts
These scripts pull csv files from various sources and should generally be the first ones you run. You can run as many or as few of these as you'd like

*** chadwick.py
pulls the [[https://github.com/chadwickbureau/register][Chadwick Register]] to allow you to translate between the various standards of player IDs. Highly recommended if you use multiple sources of baseball data (or even if you dont).

*** bref.py
pulls batter and pitcher statlines for the year specified in config.py. writes 2 separate files

*** fangraphs.py
pulls batting, pitching, and fielding data at both a player and team level. creates 6 csv files

*** retrosheet.py
pulls game logs and a table of ballpark information and codes
**** Retrosheet data notice
 The information used here was obtained free of charge from and is copyrighted by Retrosheet.  Interested parties may contact Retrosheet at "www.retrosheet.org".

*** statcast.py
pulls the full season of statcast data, including postseason. Currently this will also print a ton of warning messages due to an upstream bug in pybaseball, but it does work.
WARNING: this will result in very large CSV file if you run it for a full season (2025 is ~420MB). You can safely delete the {YEAR}\under{}statcast.csv file AFTER you run the clean\under{}statcast.py script, as that generates its own file, which is only slightly smaller.

**** clean\under{}statcast.py
will clean the statcast csv data and put it in a new file. will also print a good amount of info about the shape of the table and what it is changing. Will remove spring training/exhibition data if present. The schema of the data returned by mlb changes a couple times a season, and this cleanup script is part of ensuring we handle those changes cleanly. new additions to the schema will likely break insertion into the database, but this can likely be fixed by editing table\under{}definitions.py
note that the current csv\under{}to\under{}db.py script will only work with the cleaned version of the csv file.

** DB generation script
csv\under{}to\under{}db.py will take any of the csv files generated by the other scripts, and insert them into a sqlite database. If the database already exists, relevant tables will be overwritten.

* Query examples
There are some helper scripts in ./sql/ you can run to help augment the database. They do things like generate views, indexes, or other tables. This will probably be improved and integrated into the python scripts in the future

** Pitcher vs Batter fastball velo
find out which pitchers threw the hardest to specific batters in sample sizes of 10+ fastballs. requires ./sql/batter\under{}pitcher\under{}views.sql to have been run first
#+begin_src sql
SELECT avg(release_speed),
       count(release_speed) AS num_pitches,
       pitchers_in_chadwick_2025.name_first || ' ' || pitchers_in_chadwick_2025.name_last AS pitcher_name,
       batters_in_chadwick_2025.name_first || ' ' || batters_in_chadwick_2025.name_last AS batter_name
FROM statcast_pitches
INNER JOIN batters_in_chadwick_2025 ON statcast_pitches.batter = batters_in_chadwick_2025.key_mlbam
INNER JOIN pitchers_in_chadwick_2025 ON statcast_pitches.pitcher = pitchers_in_chadwick_2025.key_mlbam
WHERE statcast_pitches.pitch_type = 'FF'
  OR statcast_pitches.pitch_type = 'SI'
GROUP BY pitcher,
         batter
HAVING num_pitches > 10
ORDER BY avg(release_speed) DESC
#+end_src

Results:
| avg(release\under{}speed) | num\under{}pitches | pitcher\under{}name      | batter\under{}name         |
|--------------------+-------------+-------------------+---------------------|
|             101.34 |          15 | Jhoan Durán       | Shohei Ohtani       |
|   101.207692307692 |          13 | Edgardo Henriquez | Spencer Steer       |
|   101.163636363636 |          11 | Mason Miller      | Miguel Vargas       |
|   100.853846153846 |          13 | Hunter Greene     | Shohei Ohtani       |
|   100.809090909091 |          11 | Mason Miller      | Geraldo Perdomo     |
|   100.769230769231 |          13 | Jacob Misiorowski | Seiya Suzuki        |
|   100.416666666667 |          12 | Hunter Greene     | Ian Happ            |
|   100.328571428571 |          14 | Jacob Misiorowski | Kyle Tucker         |
|              100.3 |          11 | Jhoan Durán       | Jonathan Aranda     |
|          100.29375 |          16 | Jacob Misiorowski | Pete Crow-Armstrong |
|   100.218181818182 |          11 | Daniel Palencia   | Jackson Chourio     |
|            100.175 |          12 | Daniel Palencia   | Connor Norby        |
|   100.166666666667 |          12 | Daniel Palencia   | Caleb Durbin        |
|   100.116666666667 |          12 | Daniel Palencia   | TJ Friedl           |
|   100.093333333333 |          15 | Jacob Misiorowski | Matt Shaw           |
|   100.042857142857 |          21 | Hunter Greene     | Michael Busch       |
|   100.036842105263 |          19 | Jacob Misiorowski | Ian Happ            |
|   100.007142857143 |          14 | Hunter Greene     | Matt Shaw           |
|   99.9444444444444 |          18 | Jacob Misiorowski | TJ Friedl           |
|   99.9214285714286 |          14 | Aroldis Chapman   | Jazz Chisholm       |
