from statcast import index_pitches


# not sure whats best for a PK, key_mlbam + name_last is not unique and there are nulls in key_bbref
chadwick_definition = """
CREATE TABLE "chadwick" (
"name_last"	TEXT,
"name_first"	TEXT,
"key_mlbam"	INTEGER,
"key_retro"	TEXT,
"key_bbref"	TEXT,
"key_fangraphs"	INTEGER,
"mlb_played_first"	REAL,
"mlb_played_last"	REAL
);
"""

pitch_definition = """
CREATE TABLE "pitches" (
pitch_type TEXT,
game_date TEXT,
release_speed REAL,
release_pos_x REAL,
release_pos_z REAL,
player_name TEXT,
batter TEXT,
pitcher TEXT,
events TEXT,
description TEXT,
zone INTEGER,
des TEXT,
game_type TEXT,
stand TEXT,
p_throws TEXT,
home_team TEXT,
away_team TEXT,
type TEXT,
hit_location TEXT,
bb_type TEXT,
balls INTEGER,
strikes INTEGER,
game_year INTEGER,
pfx_x REAL,
pfx_z REAL,
plate_x REAL,
plate_z REAL,
on_3b TEXT,
on_2b TEXT,
on_1b TEXT,
outs_when_up INTEGER,
inning INTEGER,
inning_topbot TEXT,
hc_x REAL,
hc_y REAL,
vx0 REAL,
vy0 REAL,
vz0 REAL,
ax REAL,
ay REAL,
az REAL,
sz_top REAL,
sz_bot REAL,
hit_distance_sc REAL,
launch_speed REAL,
launch_angle REAL,
effective_speed REAL,
release_spin_rate REAL,
release_extension REAL,
game_pk INTEGER NOT NULL,
fielder_2 TEXT,
fielder_3 TEXT,
fielder_4 TEXT,
fielder_5 TEXT,
fielder_6 TEXT,
fielder_7 TEXT,
fielder_8 TEXT,
fielder_9 TEXT,
release_pos_y REAL,
estimated_ba_using_speedangle REAL,
estimated_woba_using_speedangle REAL,
woba_value REAL,
woba_denom REAL,
babip_value REAL,
iso_value REAL,
launch_speed_angle REAL,
at_bat_number INTEGER NOT NULL,
pitch_number INTEGER NOT NULL,
pitch_name TEXT,
home_score INTEGER,
away_score INTEGER,
bat_score INTEGER,
fld_score INTEGER,
post_away_score INTEGER,
post_home_score INTEGER,
post_bat_score INTEGER,
post_fld_score INTEGER,
if_fielding_alignment TEXT,
of_fielding_alignment TEXT,
spin_axis REAL,
delta_home_win_exp REAL,
delta_run_exp REAL,
bat_speed REAL,
swing_length REAL,
estimated_slg_using_speedangle REAL,
delta_pitcher_run_exp REAL,
hyper_speed REAL,
home_score_diff REAL,
bat_score_diff REAL,
home_win_exp REAL,
bat_win_exp REAL,
age_pit_legacy REAL,
age_bat_legacy REAL,
age_pit REAL,
age_bat REAL,
n_thruorder_pitcher INTEGER,
n_priorpa_thisgame_player_at_bat INTEGER,
pitcher_days_since_prev_game INTEGER,
batter_days_since_prev_game INTEGER,
pitcher_days_until_next_game INTEGER,
batter_days_until_next_game INTEGER,
api_break_z_with_gravity REAL,
api_break_x_arm REAL,
api_break_x_batter_in REAL,
arm_angle REAL,
attack_angle REAL,
attack_direction REAL,
swing_path_tilt REAL,
intercept_ball_minus_batter_pos_x_inches REAL,
intercept_ball_minus_batter_pos_y_inches REAL,
"""

#use different PK based on option in ./statcastcsv.py
if index_pitches:
    pitch_definition += """
index INTEGER PRIMARY KEY,
    """
else:
    pitch_definition += """
PRIMARY KEY (game_pk, at_bat_number, pitch_number),
    """

pitch_definition += """
FOREIGN KEY (pitcher) REFERENCES chadwick(key_mlbam),
FOREIGN KEY (batter) REFERENCES chadwick(key_mlbam)
);
"""

bref_batting_definition = """
CREATE TABLE "bref_batting" (
"Name"	TEXT,
"Age"	INTEGER,
"#days"	INTEGER,
"Lev"	TEXT,
"Tm"	TEXT,
"G"	INTEGER,
"PA"	INTEGER,
"AB"	INTEGER,
"R"	INTEGER,
"H"	INTEGER,
"2B"	INTEGER,
"3B"	INTEGER,
"HR"	INTEGER,
"RBI"	INTEGER,
"BB"	INTEGER,
"IBB"	INTEGER,
"SO"	INTEGER,
"HBP"	INTEGER,
"SH"	INTEGER,
"SF"	INTEGER,
"GDP"	INTEGER,
"SB"	INTEGER,
"CS"	INTEGER,
"BA"	REAL,
"OBP"	REAL,
"SLG"	REAL,
"OPS"	REAL,
"mlbID"	INTEGER,
PRIMARY KEY("mlbID"),
FOREIGN KEY("mlbID") REFERENCES chadwick(key_mlbam)
);
"""

bref_pitching_definition= """
CREATE TABLE "bref_pitching" (
"Name"	TEXT,
"Age"	INTEGER,
"#days"	INTEGER,
"Lev"	TEXT,
"Tm"	TEXT,
"G"	INTEGER,
"GS"	INTEGER,
"W"	REAL,
"L"	REAL,
"SV"	REAL,
"IP"	REAL,
"H"	INTEGER,
"R"	INTEGER,
"ER"	INTEGER,
"BB"	INTEGER,
"SO"	INTEGER,
"HR"	INTEGER,
"HBP"	INTEGER,
"ERA"	REAL,
"AB"	INTEGER,
"2B"	INTEGER,
"3B"	INTEGER,
"IBB"	INTEGER,
"GDP"	INTEGER,
"SF"	INTEGER,
"SB"	INTEGER,
"CS"	INTEGER,
"PO"	INTEGER,
"BF"	INTEGER,
"Pit"	INTEGER,
"Str"	REAL,
"StL"	REAL,
"StS"	REAL,
"GB/FB"	REAL,
"LD"	REAL,
"PU"	REAL,
"WHIP"	REAL,
"BAbip"	REAL,
"SO9"	REAL,
"SO/W"	REAL,
"mlbID"	INTEGER,
PRIMARY KEY("mlbID"),
FOREIGN KEY("mlbID") REFERENCES chadwick(key_mlbam)
);
"""

fangraphs_batting_definition = """
CREATE TABLE "fangraphs_batters_2025" (
	"IDfg"	INTEGER,
	"Season"	INTEGER,
	"Name"	TEXT,
	"Team"	TEXT,
	"Age"	INTEGER,
	"G"	INTEGER,
	"AB"	INTEGER,
	"PA"	INTEGER,
	"H"	INTEGER,
	"1B"	INTEGER,
	"2B"	INTEGER,
	"3B"	INTEGER,
	"HR"	INTEGER,
	"R"	INTEGER,
	"RBI"	INTEGER,
	"BB"	INTEGER,
	"IBB"	INTEGER,
	"SO"	INTEGER,
	"HBP"	INTEGER,
	"SF"	INTEGER,
	"SH"	INTEGER,
	"GDP"	INTEGER,
	"SB"	INTEGER,
	"CS"	INTEGER,
	"AVG"	REAL,
	"GB"	INTEGER,
	"FB"	INTEGER,
	"LD"	INTEGER,
	"IFFB"	INTEGER,
	"Pitches"	INTEGER,
	"Balls"	INTEGER,
	"Strikes"	INTEGER,
	"IFH"	INTEGER,
	"BU"	INTEGER,
	"BUH"	INTEGER,
	"BB%"	REAL,
	"K%"	REAL,
	"BB/K"	REAL,
	"OBP"	REAL,
	"SLG"	REAL,
	"OPS"	REAL,
	"ISO"	REAL,
	"BABIP"	REAL,
	"GB/FB"	REAL,
	"LD%"	REAL,
	"GB%"	REAL,
	"FB%"	REAL,
	"IFFB%"	REAL,
	"HR/FB"	REAL,
	"IFH%"	REAL,
	"BUH%"	REAL,
	"wOBA"	REAL,
	"wRAA"	REAL,
	"wRC"	INTEGER,
	"Bat"	REAL,
	"Fld"	TEXT,
	"Rep"	REAL,
	"Pos"	REAL,
	"RAR"	REAL,
	"WAR"	REAL,
	"Dol"	TEXT,
	"Spd"	REAL,
	"wRC+"	INTEGER,
	"WPA"	REAL,
	"-WPA"	REAL,
	"+WPA"	REAL,
	"RE24"	REAL,
	"REW"	REAL,
	"pLI"	REAL,
	"phLI"	TEXT,
	"PH"	INTEGER,
	"WPA/LI"	REAL,
	"Clutch"	REAL,
	"FB% (Pitch)"	REAL,
	"FBv"	REAL,
	"SL%"	REAL,
	"SLv"	REAL,
	"CT%"	REAL,
	"CTv"	REAL,
	"CB%"	REAL,
	"CBv"	REAL,
	"CH%"	REAL,
	"CHv"	REAL,
	"SF%"	REAL,
	"SFv"	REAL,
	"KN%"	TEXT,
	"KNv"	TEXT,
	"XX%"	REAL,
	"PO%"	TEXT,
	"wFB"	REAL,
	"wSL"	REAL,
	"wCT"	REAL,
	"wCB"	REAL,
	"wCH"	REAL,
	"wSF"	REAL,
	"wKN"	TEXT,
	"wFB/C"	REAL,
	"wSL/C"	REAL,
	"wCT/C"	REAL,
	"wCB/C"	REAL,
	"wCH/C"	REAL,
	"wSF/C"	REAL,
	"wKN/C"	TEXT,
	"O-Swing%"	REAL,
	"Z-Swing%"	REAL,
	"Swing%"	REAL,
	"O-Contact%"	REAL,
	"Z-Contact%"	REAL,
	"Contact%"	REAL,
	"Zone%"	REAL,
	"F-Strike%"	REAL,
	"SwStr%"	REAL,
	"BsR"	REAL,
	"FA% (sc)"	REAL,
	"FT% (sc)"	TEXT,
	"FC% (sc)"	REAL,
	"FS% (sc)"	REAL,
	"FO% (sc)"	TEXT,
	"SI% (sc)"	REAL,
	"SL% (sc)"	REAL,
	"CU% (sc)"	REAL,
	"KC% (sc)"	REAL,
	"EP% (sc)"	TEXT,
	"CH% (sc)"	REAL,
	"SC% (sc)"	TEXT,
	"KN% (sc)"	TEXT,
	"UN% (sc)"	TEXT,
	"vFA (sc)"	REAL,
	"vFT (sc)"	TEXT,
	"vFC (sc)"	REAL,
	"vFS (sc)"	REAL,
	"vFO (sc)"	TEXT,
	"vSI (sc)"	REAL,
	"vSL (sc)"	REAL,
	"vCU (sc)"	REAL,
	"vKC (sc)"	REAL,
	"vEP (sc)"	TEXT,
	"vCH (sc)"	REAL,
	"vSC (sc)"	TEXT,
	"vKN (sc)"	TEXT,
	"FA-X (sc)"	REAL,
	"FT-X (sc)"	TEXT,
	"FC-X (sc)"	REAL,
	"FS-X (sc)"	REAL,
	"FO-X (sc)"	TEXT,
	"SI-X (sc)"	REAL,
	"SL-X (sc)"	REAL,
	"CU-X (sc)"	REAL,
	"KC-X (sc)"	REAL,
	"EP-X (sc)"	TEXT,
	"CH-X (sc)"	REAL,
	"SC-X (sc)"	TEXT,
	"KN-X (sc)"	TEXT,
	"FA-Z (sc)"	REAL,
	"FT-Z (sc)"	TEXT,
	"FC-Z (sc)"	REAL,
	"FS-Z (sc)"	REAL,
	"FO-Z (sc)"	TEXT,
	"SI-Z (sc)"	REAL,
	"SL-Z (sc)"	REAL,
	"CU-Z (sc)"	REAL,
	"KC-Z (sc)"	REAL,
	"EP-Z (sc)"	TEXT,
	"CH-Z (sc)"	REAL,
	"SC-Z (sc)"	TEXT,
	"KN-Z (sc)"	TEXT,
	"wFA (sc)"	REAL,
	"wFT (sc)"	TEXT,
	"wFC (sc)"	REAL,
	"wFS (sc)"	REAL,
	"wFO (sc)"	TEXT,
	"wSI (sc)"	REAL,
	"wSL (sc)"	REAL,
	"wCU (sc)"	REAL,
	"wKC (sc)"	REAL,
	"wEP (sc)"	TEXT,
	"wCH (sc)"	REAL,
	"wSC (sc)"	TEXT,
	"wKN (sc)"	TEXT,
	"wFA/C (sc)"	REAL,
	"wFT/C (sc)"	TEXT,
	"wFC/C (sc)"	REAL,
	"wFS/C (sc)"	REAL,
	"wFO/C (sc)"	TEXT,
	"wSI/C (sc)"	REAL,
	"wSL/C (sc)"	REAL,
	"wCU/C (sc)"	REAL,
	"wKC/C (sc)"	REAL,
	"wEP/C (sc)"	TEXT,
	"wCH/C (sc)"	REAL,
	"wSC/C (sc)"	TEXT,
	"wKN/C (sc)"	TEXT,
	"O-Swing% (sc)"	REAL,
	"Z-Swing% (sc)"	REAL,
	"Swing% (sc)"	REAL,
	"O-Contact% (sc)"	REAL,
	"Z-Contact% (sc)"	REAL,
	"Contact% (sc)"	REAL,
	"Zone% (sc)"	REAL,
	"Pace"	REAL,
	"Def"	REAL,
	"wSB"	REAL,
	"UBR"	TEXT,
	"Age Rng"	TEXT,
	"Off"	REAL,
	"Lg"	REAL,
	"wGDP"	TEXT,
	"Pull%"	REAL,
	"Cent%"	REAL,
	"Oppo%"	REAL,
	"Soft%"	REAL,
	"Med%"	REAL,
	"Hard%"	REAL,
	"TTO%"	REAL,
	"CH% (pi)"	REAL,
	"CS% (pi)"	TEXT,
	"CU% (pi)"	REAL,
	"FA% (pi)"	REAL,
	"FC% (pi)"	REAL,
	"FS% (pi)"	REAL,
	"KN% (pi)"	TEXT,
	"SB% (pi)"	TEXT,
	"SI% (pi)"	REAL,
	"SL% (pi)"	REAL,
	"XX% (pi)"	TEXT,
	"vCH (pi)"	REAL,
	"vCS (pi)"	TEXT,
	"vCU (pi)"	REAL,
	"vFA (pi)"	REAL,
	"vFC (pi)"	REAL,
	"vFS (pi)"	REAL,
	"vKN (pi)"	TEXT,
	"vSB (pi)"	TEXT,
	"vSI (pi)"	REAL,
	"vSL (pi)"	REAL,
	"vXX (pi)"	TEXT,
	"CH-X (pi)"	REAL,
	"CS-X (pi)"	TEXT,
	"CU-X (pi)"	REAL,
	"FA-X (pi)"	REAL,
	"FC-X (pi)"	REAL,
	"FS-X (pi)"	REAL,
	"KN-X (pi)"	TEXT,
	"SB-X (pi)"	TEXT,
	"SI-X (pi)"	REAL,
	"SL-X (pi)"	REAL,
	"XX-X (pi)"	TEXT,
	"CH-Z (pi)"	REAL,
	"CS-Z (pi)"	TEXT,
	"CU-Z (pi)"	REAL,
	"FA-Z (pi)"	REAL,
	"FC-Z (pi)"	REAL,
	"FS-Z (pi)"	REAL,
	"KN-Z (pi)"	TEXT,
	"SB-Z (pi)"	TEXT,
	"SI-Z (pi)"	REAL,
	"SL-Z (pi)"	REAL,
	"XX-Z (pi)"	TEXT,
	"wCH (pi)"	REAL,
	"wCS (pi)"	TEXT,
	"wCU (pi)"	REAL,
	"wFA (pi)"	REAL,
	"wFC (pi)"	REAL,
	"wFS (pi)"	REAL,
	"wKN (pi)"	TEXT,
	"wSB (pi)"	TEXT,
	"wSI (pi)"	REAL,
	"wSL (pi)"	REAL,
	"wXX (pi)"	TEXT,
	"wCH/C (pi)"	REAL,
	"wCS/C (pi)"	TEXT,
	"wCU/C (pi)"	REAL,
	"wFA/C (pi)"	REAL,
	"wFC/C (pi)"	REAL,
	"wFS/C (pi)"	REAL,
	"wKN/C (pi)"	TEXT,
	"wSB/C (pi)"	TEXT,
	"wSI/C (pi)"	REAL,
	"wSL/C (pi)"	REAL,
	"wXX/C (pi)"	TEXT,
	"O-Swing% (pi)"	REAL,
	"Z-Swing% (pi)"	REAL,
	"Swing% (pi)"	REAL,
	"O-Contact% (pi)"	REAL,
	"Z-Contact% (pi)"	REAL,
	"Contact% (pi)"	REAL,
	"Zone% (pi)"	REAL,
	"Pace (pi)"	REAL,
	"FRM"	TEXT,
	"AVG+"	INTEGER,
	"BB%+"	INTEGER,
	"K%+"	INTEGER,
	"OBP+"	INTEGER,
	"SLG+"	INTEGER,
	"ISO+"	INTEGER,
	"BABIP+"	INTEGER,
	"LD+%"	REAL,
	"GB%+"	INTEGER,
	"FB%+"	INTEGER,
	"HR/FB%+"	INTEGER,
	"Pull%+"	INTEGER,
	"Cent%+"	INTEGER,
	"Oppo%+"	INTEGER,
	"Soft%+"	INTEGER,
	"Med%+"	INTEGER,
	"Hard%+"	INTEGER,
	"EV"	REAL,
	"LA"	REAL,
	"Barrels"	INTEGER,
	"Barrel%"	REAL,
	"maxEV"	REAL,
	"HardHit"	INTEGER,
	"HardHit%"	REAL,
	"Events"	INTEGER,
	"CStr%"	REAL,
	"CSW%"	REAL,
	"xBA"	REAL,
	"xSLG"	REAL,
	"xwOBA"	REAL,
	"L-WAR"	REAL,
	PRIMARY KEY("IDfg")
);
"""

fangraphs_pitching_definition = """
CREATE TABLE "fangraphs_pitcher_2025" (
	"IDfg"	INTEGER,
	"Season"	INTEGER,
	"Name"	TEXT,
	"Team"	TEXT,
	"Age"	INTEGER,
	"W"	INTEGER,
	"L"	INTEGER,
	"WAR"	REAL,
	"ERA"	REAL,
	"G"	INTEGER,
	"GS"	INTEGER,
	"CG"	INTEGER,
	"ShO"	INTEGER,
	"SV"	INTEGER,
	"BS"	INTEGER,
	"IP"	REAL,
	"TBF"	INTEGER,
	"H"	INTEGER,
	"R"	INTEGER,
	"ER"	INTEGER,
	"HR"	INTEGER,
	"BB"	INTEGER,
	"IBB"	INTEGER,
	"HBP"	INTEGER,
	"WP"	INTEGER,
	"BK"	INTEGER,
	"SO"	INTEGER,
	"GB"	INTEGER,
	"FB"	INTEGER,
	"LD"	INTEGER,
	"IFFB"	INTEGER,
	"Balls"	INTEGER,
	"Strikes"	INTEGER,
	"Pitches"	INTEGER,
	"RS"	INTEGER,
	"IFH"	INTEGER,
	"BU"	INTEGER,
	"BUH"	INTEGER,
	"K/9"	REAL,
	"BB/9"	REAL,
	"K/BB"	REAL,
	"H/9"	REAL,
	"HR/9"	REAL,
	"AVG"	REAL,
	"WHIP"	REAL,
	"BABIP"	REAL,
	"LOB%"	REAL,
	"FIP"	REAL,
	"GB/FB"	REAL,
	"LD%"	REAL,
	"GB%"	REAL,
	"FB%"	REAL,
	"IFFB%"	REAL,
	"HR/FB"	REAL,
	"IFH%"	REAL,
	"BUH%"	REAL,
	"Starting"	REAL,
	"Start-IP"	REAL,
	"Relieving"	TEXT,
	"Relief-IP"	TEXT,
	"RAR"	REAL,
	"Dollars"	TEXT,
	"tERA"	REAL,
	"xFIP"	REAL,
	"WPA"	REAL,
	"-WPA"	REAL,
	"+WPA"	REAL,
	"RE24"	REAL,
	"REW"	REAL,
	"pLI"	REAL,
	"inLI"	REAL,
	"gmLI"	REAL,
	"exLI"	REAL,
	"Pulls"	INTEGER,
	"WPA/LI"	REAL,
	"Clutch"	REAL,
	"FB% 2"	REAL,
	"FBv"	REAL,
	"SL%"	TEXT,
	"SLv"	TEXT,
	"CT%"	TEXT,
	"CTv"	TEXT,
	"CB%"	TEXT,
	"CBv"	TEXT,
	"CH%"	TEXT,
	"CHv"	TEXT,
	"SF%"	TEXT,
	"SFv"	TEXT,
	"KN%"	TEXT,
	"KNv"	TEXT,
	"XX%"	TEXT,
	"PO%"	TEXT,
	"wFB"	REAL,
	"wSL"	TEXT,
	"wCT"	TEXT,
	"wCB"	TEXT,
	"wCH"	TEXT,
	"wSF"	TEXT,
	"wKN"	TEXT,
	"wFB/C"	REAL,
	"wSL/C"	TEXT,
	"wCT/C"	TEXT,
	"wCB/C"	TEXT,
	"wCH/C"	TEXT,
	"wSF/C"	TEXT,
	"wKN/C"	TEXT,
	"O-Swing%"	REAL,
	"Z-Swing%"	REAL,
	"Swing%"	REAL,
	"O-Contact%"	REAL,
	"Z-Contact%"	REAL,
	"Contact%"	REAL,
	"Zone%"	REAL,
	"F-Strike%"	REAL,
	"SwStr%"	REAL,
	"HLD"	INTEGER,
	"SD"	INTEGER,
	"MD"	INTEGER,
	"ERA-"	INTEGER,
	"FIP-"	INTEGER,
	"xFIP-"	INTEGER,
	"K%"	REAL,
	"BB%"	REAL,
	"SIERA"	REAL,
	"RS/9"	REAL,
	"E-F"	REAL,
	"FA% (sc)"	TEXT,
	"FT% (sc)"	TEXT,
	"FC% (sc)"	TEXT,
	"FS% (sc)"	TEXT,
	"FO% (sc)"	TEXT,
	"SI% (sc)"	TEXT,
	"SL% (sc)"	REAL,
	"CU% (sc)"	TEXT,
	"KC% (sc)"	TEXT,
	"EP% (sc)"	TEXT,
	"CH% (sc)"	TEXT,
	"SC% (sc)"	TEXT,
	"KN% (sc)"	TEXT,
	"UN% (sc)"	TEXT,
	"vFA (sc)"	TEXT,
	"vFT (sc)"	TEXT,
	"vFC (sc)"	TEXT,
	"vFS (sc)"	TEXT,
	"vFO (sc)"	TEXT,
	"vSI (sc)"	TEXT,
	"vSL (sc)"	REAL,
	"vCU (sc)"	TEXT,
	"vKC (sc)"	TEXT,
	"vEP (sc)"	TEXT,
	"vCH (sc)"	TEXT,
	"vSC (sc)"	TEXT,
	"vKN (sc)"	TEXT,
	"FA-X (sc)"	TEXT,
	"FT-X (sc)"	TEXT,
	"FC-X (sc)"	TEXT,
	"FS-X (sc)"	TEXT,
	"FO-X (sc)"	TEXT,
	"SI-X (sc)"	TEXT,
	"SL-X (sc)"	REAL,
	"CU-X (sc)"	TEXT,
	"KC-X (sc)"	TEXT,
	"EP-X (sc)"	TEXT,
	"CH-X (sc)"	TEXT,
	"SC-X (sc)"	TEXT,
	"KN-X (sc)"	TEXT,
	"FA-Z (sc)"	TEXT,
	"FT-Z (sc)"	TEXT,
	"FC-Z (sc)"	TEXT,
	"FS-Z (sc)"	TEXT,
	"FO-Z (sc)"	TEXT,
	"SI-Z (sc)"	TEXT,
	"SL-Z (sc)"	REAL,
	"CU-Z (sc)"	TEXT,
	"KC-Z (sc)"	TEXT,
	"EP-Z (sc)"	TEXT,
	"CH-Z (sc)"	TEXT,
	"SC-Z (sc)"	TEXT,
	"KN-Z (sc)"	TEXT,
	"wFA (sc)"	TEXT,
	"wFT (sc)"	TEXT,
	"wFC (sc)"	TEXT,
	"wFS (sc)"	TEXT,
	"wFO (sc)"	TEXT,
	"wSI (sc)"	TEXT,
	"wSL (sc)"	REAL,
	"wCU (sc)"	TEXT,
	"wKC (sc)"	TEXT,
	"wEP (sc)"	TEXT,
	"wCH (sc)"	TEXT,
	"wSC (sc)"	TEXT,
	"wKN (sc)"	TEXT,
	"wFA/C (sc)"	TEXT,
	"wFT/C (sc)"	TEXT,
	"wFC/C (sc)"	TEXT,
	"wFS/C (sc)"	TEXT,
	"wFO/C (sc)"	TEXT,
	"wSI/C (sc)"	TEXT,
	"wSL/C (sc)"	REAL,
	"wCU/C (sc)"	TEXT,
	"wKC/C (sc)"	TEXT,
	"wEP/C (sc)"	TEXT,
	"wCH/C (sc)"	TEXT,
	"wSC/C (sc)"	TEXT,
	"wKN/C (sc)"	TEXT,
	"O-Swing% (sc)"	REAL,
	"Z-Swing% (sc)"	REAL,
	"Swing% (sc)"	REAL,
	"O-Contact% (sc)"	REAL,
	"Z-Contact% (sc)"	REAL,
	"Contact% (sc)"	REAL,
	"Zone% (sc)"	REAL,
	"Pace"	REAL,
	"RA9-WAR"	REAL,
	"BIP-Wins"	REAL,
	"LOB-Wins"	REAL,
	"FDP-Wins"	REAL,
	"Age Rng"	TEXT,
	"K-BB%"	REAL,
	"Pull%"	REAL,
	"Cent%"	REAL,
	"Oppo%"	REAL,
	"Soft%"	REAL,
	"Med%"	REAL,
	"Hard%"	REAL,
	"kwERA"	REAL,
	"TTO%"	REAL,
	"CH% (pi)"	TEXT,
	"CS% (pi)"	TEXT,
	"CU% (pi)"	TEXT,
	"FA% (pi)"	TEXT,
	"FC% (pi)"	TEXT,
	"FS% (pi)"	TEXT,
	"KN% (pi)"	TEXT,
	"SB% (pi)"	TEXT,
	"SI% (pi)"	TEXT,
	"SL% (pi)"	REAL,
	"XX% (pi)"	TEXT,
	"vCH (pi)"	TEXT,
	"vCS (pi)"	TEXT,
	"vCU (pi)"	TEXT,
	"vFA (pi)"	TEXT,
	"vFC (pi)"	TEXT,
	"vFS (pi)"	TEXT,
	"vKN (pi)"	TEXT,
	"vSB (pi)"	TEXT,
	"vSI (pi)"	TEXT,
	"vSL (pi)"	REAL,
	"vXX (pi)"	TEXT,
	"CH-X (pi)"	TEXT,
	"CS-X (pi)"	TEXT,
	"CU-X (pi)"	TEXT,
	"FA-X (pi)"	TEXT,
	"FC-X (pi)"	TEXT,
	"FS-X (pi)"	TEXT,
	"KN-X (pi)"	TEXT,
	"SB-X (pi)"	TEXT,
	"SI-X (pi)"	TEXT,
	"SL-X (pi)"	REAL,
	"XX-X (pi)"	TEXT,
	"CH-Z (pi)"	TEXT,
	"CS-Z (pi)"	TEXT,
	"CU-Z (pi)"	TEXT,
	"FA-Z (pi)"	TEXT,
	"FC-Z (pi)"	TEXT,
	"FS-Z (pi)"	TEXT,
	"KN-Z (pi)"	TEXT,
	"SB-Z (pi)"	TEXT,
	"SI-Z (pi)"	TEXT,
	"SL-Z (pi)"	REAL,
	"XX-Z (pi)"	TEXT,
	"wCH (pi)"	TEXT,
	"wCS (pi)"	TEXT,
	"wCU (pi)"	TEXT,
	"wFA (pi)"	TEXT,
	"wFC (pi)"	TEXT,
	"wFS (pi)"	TEXT,
	"wKN (pi)"	TEXT,
	"wSB (pi)"	TEXT,
	"wSI (pi)"	TEXT,
	"wSL (pi)"	REAL,
	"wXX (pi)"	TEXT,
	"wCH/C (pi)"	TEXT,
	"wCS/C (pi)"	TEXT,
	"wCU/C (pi)"	TEXT,
	"wFA/C (pi)"	TEXT,
	"wFC/C (pi)"	TEXT,
	"wFS/C (pi)"	TEXT,
	"wKN/C (pi)"	TEXT,
	"wSB/C (pi)"	TEXT,
	"wSI/C (pi)"	TEXT,
	"wSL/C (pi)"	REAL,
	"wXX/C (pi)"	TEXT,
	"O-Swing% (pi)"	REAL,
	"Z-Swing% (pi)"	REAL,
	"Swing% (pi)"	REAL,
	"O-Contact% (pi)"	REAL,
	"Z-Contact% (pi)"	REAL,
	"Contact% (pi)"	REAL,
	"Zone% (pi)"	REAL,
	"Pace (pi)"	REAL,
	"FRM"	REAL,
	"K/9+"	INTEGER,
	"BB/9+"	INTEGER,
	"K/BB+"	INTEGER,
	"H/9+"	INTEGER,
	"HR/9+"	INTEGER,
	"AVG+"	INTEGER,
	"WHIP+"	INTEGER,
	"BABIP+"	INTEGER,
	"LOB%+"	INTEGER,
	"K%+"	INTEGER,
	"BB%+"	INTEGER,
	"LD%+"	INTEGER,
	"GB%+"	INTEGER,
	"FB%+"	INTEGER,
	"HR/FB%+"	INTEGER,
	"Pull%+"	INTEGER,
	"Cent%+"	INTEGER,
	"Oppo%+"	INTEGER,
	"Soft%+"	INTEGER,
	"Med%+"	INTEGER,
	"Hard%+"	INTEGER,
	"EV"	REAL,
	"LA"	REAL,
	"Barrels"	INTEGER,
	"Barrel%"	REAL,
	"maxEV"	REAL,
	"HardHit"	INTEGER,
	"HardHit%"	REAL,
	"Events"	INTEGER,
	"CStr%"	REAL,
	"CSW%"	REAL,
	"xERA"	REAL,
	"botERA"	REAL,
	"botOvr CH"	TEXT,
	"botStf CH"	TEXT,
	"botCmd CH"	TEXT,
	"botOvr CU"	TEXT,
	"botStf CU"	TEXT,
	"botCmd CU"	TEXT,
	"botOvr FA"	TEXT,
	"botStf FA"	TEXT,
	"botCmd FA"	TEXT,
	"botOvr SI"	TEXT,
	"botStf SI"	TEXT,
	"botCmd SI"	TEXT,
	"botOvr SL"	REAL,
	"botStf SL"	REAL,
	"botCmd SL"	REAL,
	"botOvr KC"	TEXT,
	"botStf KC"	TEXT,
	"botCmd KC"	TEXT,
	"botOvr FC"	TEXT,
	"botStf FC"	TEXT,
	"botCmd FC"	TEXT,
	"botOvr FS"	TEXT,
	"botStf FS"	TEXT,
	"botCmd FS"	TEXT,
	"botOvr"	INTEGER,
	"botStf"	INTEGER,
	"botCmd"	INTEGER,
	"botxRV100"	REAL,
	"Stf+ CH"	TEXT,
	"Loc+ CH"	TEXT,
	"Pit+ CH"	TEXT,
	"Stf+ CU"	TEXT,
	"Loc+ CU"	TEXT,
	"Pit+ CU"	TEXT,
	"Stf+ FA"	TEXT,
	"Loc+ FA"	TEXT,
	"Pit+ FA"	TEXT,
	"Stf+ SI"	TEXT,
	"Loc+ SI"	TEXT,
	"Pit+ SI"	TEXT,
	"Stf+ SL"	REAL,
	"Loc+ SL"	REAL,
	"Pit+ SL"	REAL,
	"Stf+ KC"	TEXT,
	"Loc+ KC"	TEXT,
	"Pit+ KC"	TEXT,
	"Stf+ FC"	TEXT,
	"Loc+ FC"	TEXT,
	"Pit+ FC"	TEXT,
	"Stf+ FS"	TEXT,
	"Loc+ FS"	TEXT,
	"Pit+ FS"	TEXT,
	"Stuff+"	INTEGER,
	"Location+"	INTEGER,
	"Pitching+"	INTEGER,
	"Stf+ FO"	TEXT,
	"Loc+ FO"	TEXT,
	"Pit+ FO"	TEXT,
	PRIMARY KEY("IDfg")
);
"""

fangraphs_fielding_definition = """
CREATE TABLE "fangraphs_fielder_2025" (
	"IDfg"	INTEGER,
	"Season"	INTEGER,
	"Name"	TEXT,
	"Team"	TEXT,
	"Pos"	TEXT,
	"G"	INTEGER,
	"GS"	INTEGER,
	"Inn"	REAL,
	"PO"	INTEGER,
	"A"	INTEGER,
	"E"	INTEGER,
	"FE"	INTEGER,
	"TE"	INTEGER,
	"DP"	INTEGER,
	"DPS"	INTEGER,
	"DPT"	INTEGER,
	"DPF"	INTEGER,
	"Scp"	TEXT,
	"SB"	TEXT,
	"CS"	TEXT,
	"PB"	TEXT,
	"WP"	TEXT,
	"FP"	REAL,
	"TZ"	TEXT,
	"rSB"	TEXT,
	"rGDP"	TEXT,
	"rARM"	TEXT,
	"rGFP"	INTEGER,
	"rPM"	TEXT,
	"DRS"	INTEGER,
	"BIZ"	TEXT,
	"Plays"	TEXT,
	"RZR"	TEXT,
	"OOZ"	TEXT,
	"TZL"	TEXT,
	"FSR"	TEXT,
	"ARM"	TEXT,
	"DPR"	TEXT,
	"RngR"	TEXT,
	"ErrR"	TEXT,
	"UZR"	TEXT,
	"UZR/150"	TEXT,
	"CPP"	TEXT,
	"RPP"	TEXT,
	"Def"	REAL,
	"0%"	TEXT,
	"# 0%"	TEXT,
	"1-10%"	TEXT,
	"# 1-10%"	TEXT,
	"10-40%"	TEXT,
	"# 10-40%"	TEXT,
	"40-60%"	TEXT,
	"# 40-60%"	TEXT,
	"60-90%"	TEXT,
	"# 60-90%"	TEXT,
	"90-100%"	TEXT,
	"# 90-100%"	TEXT,
	"rSZ"	INTEGER,
	"rCERA"	TEXT,
	"rTS"	TEXT,
	"FRM"	TEXT,
	"OAA"	TEXT,
	"Range"	TEXT,
	PRIMARY KEY("IDfg")
);
"""

fangraphs_team_batting_definition = """
CREATE TABLE "fangraphs_fielder_2025" (
	"IDfg"	INTEGER,
	"Season"	INTEGER,
	"Name"	TEXT,
	"Team"	TEXT,
	"Pos"	TEXT,
	"G"	INTEGER,
	"GS"	INTEGER,
	"Inn"	REAL,
	"PO"	INTEGER,
	"A"	INTEGER,
	"E"	INTEGER,
	"FE"	INTEGER,
	"TE"	INTEGER,
	"DP"	INTEGER,
	"DPS"	INTEGER,
	"DPT"	INTEGER,
	"DPF"	INTEGER,
	"Scp"	TEXT,
	"SB"	TEXT,
	"CS"	TEXT,
	"PB"	TEXT,
	"WP"	TEXT,
	"FP"	REAL,
	"TZ"	TEXT,
	"rSB"	TEXT,
	"rGDP"	TEXT,
	"rARM"	TEXT,
	"rGFP"	INTEGER,
	"rPM"	TEXT,
	"DRS"	INTEGER,
	"BIZ"	TEXT,
	"Plays"	TEXT,
	"RZR"	TEXT,
	"OOZ"	TEXT,
	"TZL"	TEXT,
	"FSR"	TEXT,
	"ARM"	TEXT,
	"DPR"	TEXT,
	"RngR"	TEXT,
	"ErrR"	TEXT,
	"UZR"	TEXT,
	"UZR/150"	TEXT,
	"CPP"	TEXT,
	"RPP"	TEXT,
	"Def"	REAL,
	"0%"	TEXT,
	"# 0%"	TEXT,
	"1-10%"	TEXT,
	"# 1-10%"	TEXT,
	"10-40%"	TEXT,
	"# 10-40%"	TEXT,
	"40-60%"	TEXT,
	"# 40-60%"	TEXT,
	"60-90%"	TEXT,
	"# 60-90%"	TEXT,
	"90-100%"	TEXT,
	"# 90-100%"	TEXT,
	"rSZ"	INTEGER,
	"rCERA"	TEXT,
	"rTS"	TEXT,
	"FRM"	TEXT,
	"OAA"	TEXT,
	"Range"	TEXT,
	PRIMARY KEY("IDfg")
);
"""

fangraphs_team_pitching_definition = """
CREATE TABLE "fangraphs_team_pitching_2025" (
	"teamIDfg"	INTEGER,
	"Season"	INTEGER,
	"Team"	TEXT,
	"Age"	INTEGER,
	"W"	INTEGER,
	"L"	INTEGER,
	"ERA"	REAL,
	"G"	INTEGER,
	"GS"	INTEGER,
	"CG"	INTEGER,
	"ShO"	INTEGER,
	"SV"	INTEGER,
	"BS"	INTEGER,
	"IP"	REAL,
	"TBF"	INTEGER,
	"H"	INTEGER,
	"R"	INTEGER,
	"ER"	INTEGER,
	"HR"	INTEGER,
	"BB"	INTEGER,
	"IBB"	INTEGER,
	"HBP"	INTEGER,
	"WP"	INTEGER,
	"BK"	INTEGER,
	"SO"	INTEGER,
	"GB"	INTEGER,
	"FB"	INTEGER,
	"LD"	INTEGER,
	"IFFB"	INTEGER,
	"Balls"	INTEGER,
	"Strikes"	INTEGER,
	"Pitches"	INTEGER,
	"RS"	INTEGER,
	"IFH"	INTEGER,
	"BU"	INTEGER,
	"BUH"	INTEGER,
	"K/9"	REAL,
	"BB/9"	REAL,
	"K/BB"	REAL,
	"H/9"	REAL,
	"HR/9"	REAL,
	"AVG"	REAL,
	"WHIP"	REAL,
	"BABIP"	REAL,
	"LOB%"	REAL,
	"FIP"	REAL,
	"GB/FB"	REAL,
	"LD%"	REAL,
	"GB%"	REAL,
	"FB%"	REAL,
	"IFFB%"	REAL,
	"HR/FB"	REAL,
	"IFH%"	REAL,
	"BUH%"	REAL,
	"Starting"	REAL,
	"Start-IP"	REAL,
	"Relieving"	REAL,
	"Relief-IP"	REAL,
	"RAR"	REAL,
	"WAR"	REAL,
	"Dollars"	TEXT,
	"tERA"	REAL,
	"xFIP"	REAL,
	"WPA"	REAL,
	"-WPA"	REAL,
	"+WPA"	REAL,
	"RE24"	REAL,
	"REW"	REAL,
	"pLI"	REAL,
	"inLI"	REAL,
	"gmLI"	REAL,
	"exLI"	REAL,
	"Pulls"	INTEGER,
	"WPA/LI"	REAL,
	"Clutch"	REAL,
	"FB% 2"	REAL,
	"FBv"	REAL,
	"SL%"	REAL,
	"SLv"	REAL,
	"CT%"	REAL,
	"CTv"	REAL,
	"CB%"	REAL,
	"CBv"	REAL,
	"CH%"	REAL,
	"CHv"	REAL,
	"SF%"	REAL,
	"SFv"	REAL,
	"KN%"	TEXT,
	"KNv"	TEXT,
	"XX%"	REAL,
	"PO%"	TEXT,
	"wFB"	REAL,
	"wSL"	REAL,
	"wCT"	REAL,
	"wCB"	REAL,
	"wCH"	REAL,
	"wSF"	REAL,
	"wKN"	TEXT,
	"wFB/C"	REAL,
	"wSL/C"	REAL,
	"wCT/C"	REAL,
	"wCB/C"	REAL,
	"wCH/C"	REAL,
	"wSF/C"	REAL,
	"wKN/C"	TEXT,
	"O-Swing%"	REAL,
	"Z-Swing%"	REAL,
	"Swing%"	REAL,
	"O-Contact%"	REAL,
	"Z-Contact%"	REAL,
	"Contact%"	REAL,
	"Zone%"	REAL,
	"F-Strike%"	REAL,
	"SwStr%"	REAL,
	"HLD"	INTEGER,
	"SD"	INTEGER,
	"MD"	INTEGER,
	"ERA-"	INTEGER,
	"FIP-"	INTEGER,
	"xFIP-"	INTEGER,
	"K%"	REAL,
	"BB%"	REAL,
	"SIERA"	REAL,
	"RS/9"	REAL,
	"E-F"	REAL,
	"FA% (sc)"	REAL,
	"FT% (sc)"	TEXT,
	"FC% (sc)"	REAL,
	"FS% (sc)"	REAL,
	"FO% (sc)"	TEXT,
	"SI% (sc)"	REAL,
	"SL% (sc)"	REAL,
	"CU% (sc)"	REAL,
	"KC% (sc)"	TEXT,
	"EP% (sc)"	TEXT,
	"CH% (sc)"	REAL,
	"SC% (sc)"	TEXT,
	"KN% (sc)"	TEXT,
	"UN% (sc)"	TEXT,
	"vFA (sc)"	REAL,
	"vFT (sc)"	TEXT,
	"vFC (sc)"	REAL,
	"vFS (sc)"	REAL,
	"vFO (sc)"	TEXT,
	"vSI (sc)"	REAL,
	"vSL (sc)"	REAL,
	"vCU (sc)"	REAL,
	"vKC (sc)"	TEXT,
	"vEP (sc)"	TEXT,
	"vCH (sc)"	REAL,
	"vSC (sc)"	TEXT,
	"vKN (sc)"	TEXT,
	"FA-X (sc)"	REAL,
	"FT-X (sc)"	TEXT,
	"FC-X (sc)"	REAL,
	"FS-X (sc)"	REAL,
	"FO-X (sc)"	TEXT,
	"SI-X (sc)"	REAL,
	"SL-X (sc)"	REAL,
	"CU-X (sc)"	REAL,
	"KC-X (sc)"	TEXT,
	"EP-X (sc)"	TEXT,
	"CH-X (sc)"	REAL,
	"SC-X (sc)"	TEXT,
	"KN-X (sc)"	TEXT,
	"FA-Z (sc)"	REAL,
	"FT-Z (sc)"	TEXT,
	"FC-Z (sc)"	REAL,
	"FS-Z (sc)"	REAL,
	"FO-Z (sc)"	TEXT,
	"SI-Z (sc)"	REAL,
	"SL-Z (sc)"	REAL,
	"CU-Z (sc)"	REAL,
	"KC-Z (sc)"	TEXT,
	"EP-Z (sc)"	TEXT,
	"CH-Z (sc)"	REAL,
	"SC-Z (sc)"	TEXT,
	"KN-Z (sc)"	TEXT,
	"wFA (sc)"	REAL,
	"wFT (sc)"	TEXT,
	"wFC (sc)"	REAL,
	"wFS (sc)"	REAL,
	"wFO (sc)"	TEXT,
	"wSI (sc)"	REAL,
	"wSL (sc)"	REAL,
	"wCU (sc)"	REAL,
	"wKC (sc)"	TEXT,
	"wEP (sc)"	TEXT,
	"wCH (sc)"	REAL,
	"wSC (sc)"	TEXT,
	"wKN (sc)"	TEXT,
	"wFA/C (sc)"	REAL,
	"wFT/C (sc)"	TEXT,
	"wFC/C (sc)"	REAL,
	"wFS/C (sc)"	REAL,
	"wFO/C (sc)"	TEXT,
	"wSI/C (sc)"	REAL,
	"wSL/C (sc)"	REAL,
	"wCU/C (sc)"	REAL,
	"wKC/C (sc)"	TEXT,
	"wEP/C (sc)"	TEXT,
	"wCH/C (sc)"	REAL,
	"wSC/C (sc)"	TEXT,
	"wKN/C (sc)"	TEXT,
	"O-Swing% (sc)"	REAL,
	"Z-Swing% (sc)"	REAL,
	"Swing% (sc)"	REAL,
	"O-Contact% (sc)"	REAL,
	"Z-Contact% (sc)"	REAL,
	"Contact% (sc)"	REAL,
	"Zone% (sc)"	REAL,
	"Pace"	REAL,
	"RA9-WAR"	REAL,
	"BIP-Wins"	REAL,
	"LOB-Wins"	REAL,
	"FDP-Wins"	REAL,
	"Age Rng"	TEXT,
	"K-BB%"	REAL,
	"Pull%"	REAL,
	"Cent%"	REAL,
	"Oppo%"	REAL,
	"Soft%"	REAL,
	"Med%"	REAL,
	"Hard%"	REAL,
	"kwERA"	REAL,
	"TTO%"	REAL,
	"CH% (pi)"	REAL,
	"CS% (pi)"	TEXT,
	"CU% (pi)"	REAL,
	"FA% (pi)"	REAL,
	"FC% (pi)"	REAL,
	"FS% (pi)"	REAL,
	"KN% (pi)"	TEXT,
	"SB% (pi)"	TEXT,
	"SI% (pi)"	REAL,
	"SL% (pi)"	REAL,
	"XX% (pi)"	TEXT,
	"vCH (pi)"	REAL,
	"vCS (pi)"	TEXT,
	"vCU (pi)"	REAL,
	"vFA (pi)"	REAL,
	"vFC (pi)"	REAL,
	"vFS (pi)"	REAL,
	"vKN (pi)"	TEXT,
	"vSB (pi)"	TEXT,
	"vSI (pi)"	REAL,
	"vSL (pi)"	REAL,
	"vXX (pi)"	TEXT,
	"CH-X (pi)"	REAL,
	"CS-X (pi)"	TEXT,
	"CU-X (pi)"	REAL,
	"FA-X (pi)"	REAL,
	"FC-X (pi)"	REAL,
	"FS-X (pi)"	REAL,
	"KN-X (pi)"	TEXT,
	"SB-X (pi)"	TEXT,
	"SI-X (pi)"	REAL,
	"SL-X (pi)"	REAL,
	"XX-X (pi)"	TEXT,
	"CH-Z (pi)"	REAL,
	"CS-Z (pi)"	TEXT,
	"CU-Z (pi)"	REAL,
	"FA-Z (pi)"	REAL,
	"FC-Z (pi)"	REAL,
	"FS-Z (pi)"	REAL,
	"KN-Z (pi)"	TEXT,
	"SB-Z (pi)"	TEXT,
	"SI-Z (pi)"	REAL,
	"SL-Z (pi)"	REAL,
	"XX-Z (pi)"	TEXT,
	"wCH (pi)"	REAL,
	"wCS (pi)"	TEXT,
	"wCU (pi)"	REAL,
	"wFA (pi)"	REAL,
	"wFC (pi)"	REAL,
	"wFS (pi)"	REAL,
	"wKN (pi)"	TEXT,
	"wSB (pi)"	TEXT,
	"wSI (pi)"	REAL,
	"wSL (pi)"	REAL,
	"wXX (pi)"	TEXT,
	"wCH/C (pi)"	REAL,
	"wCS/C (pi)"	TEXT,
	"wCU/C (pi)"	REAL,
	"wFA/C (pi)"	REAL,
	"wFC/C (pi)"	REAL,
	"wFS/C (pi)"	REAL,
	"wKN/C (pi)"	TEXT,
	"wSB/C (pi)"	TEXT,
	"wSI/C (pi)"	REAL,
	"wSL/C (pi)"	REAL,
	"wXX/C (pi)"	TEXT,
	"O-Swing% (pi)"	REAL,
	"Z-Swing% (pi)"	REAL,
	"Swing% (pi)"	REAL,
	"O-Contact% (pi)"	REAL,
	"Z-Contact% (pi)"	REAL,
	"Contact% (pi)"	REAL,
	"Zone% (pi)"	REAL,
	"Pace (pi)"	REAL,
	"FRM"	REAL,
	"K/9+"	INTEGER,
	"BB/9+"	INTEGER,
	"K/BB+"	INTEGER,
	"H/9+"	INTEGER,
	"HR/9+"	INTEGER,
	"AVG+"	INTEGER,
	"WHIP+"	INTEGER,
	"BABIP+"	INTEGER,
	"LOB%+"	INTEGER,
	"K%+"	INTEGER,
	"BB%+"	INTEGER,
	"LD%+"	INTEGER,
	"GB%+"	INTEGER,
	"FB%+"	INTEGER,
	"HR/FB%+"	INTEGER,
	"Pull%+"	INTEGER,
	"Cent%+"	INTEGER,
	"Oppo%+"	INTEGER,
	"Soft%+"	INTEGER,
	"Med%+"	INTEGER,
	"Hard%+"	INTEGER,
	"EV"	REAL,
	"LA"	REAL,
	"Barrels"	INTEGER,
	"Barrel%"	REAL,
	"maxEV"	REAL,
	"HardHit"	INTEGER,
	"HardHit%"	REAL,
	"Events"	INTEGER,
	"CStr%"	REAL,
	"CSW%"	REAL,
	"xERA"	REAL,
	"botERA"	REAL,
	"botOvr CH"	INTEGER,
	"botStf CH"	INTEGER,
	"botCmd CH"	INTEGER,
	"botOvr CU"	INTEGER,
	"botStf CU"	INTEGER,
	"botCmd CU"	INTEGER,
	"botOvr FA"	INTEGER,
	"botStf FA"	INTEGER,
	"botCmd FA"	INTEGER,
	"botOvr SI"	INTEGER,
	"botStf SI"	INTEGER,
	"botCmd SI"	INTEGER,
	"botOvr SL"	INTEGER,
	"botStf SL"	INTEGER,
	"botCmd SL"	INTEGER,
	"botOvr KC"	TEXT,
	"botStf KC"	TEXT,
	"botCmd KC"	TEXT,
	"botOvr FC"	INTEGER,
	"botStf FC"	INTEGER,
	"botCmd FC"	INTEGER,
	"botOvr FS"	REAL,
	"botStf FS"	REAL,
	"botCmd FS"	REAL,
	"botOvr"	INTEGER,
	"botStf"	INTEGER,
	"botCmd"	INTEGER,
	"botxRV100"	REAL,
	"Stf+ CH"	INTEGER,
	"Loc+ CH"	INTEGER,
	"Pit+ CH"	INTEGER,
	"Stf+ CU"	INTEGER,
	"Loc+ CU"	INTEGER,
	"Pit+ CU"	INTEGER,
	"Stf+ FA"	INTEGER,
	"Loc+ FA"	INTEGER,
	"Pit+ FA"	INTEGER,
	"Stf+ SI"	INTEGER,
	"Loc+ SI"	INTEGER,
	"Pit+ SI"	INTEGER,
	"Stf+ SL"	INTEGER,
	"Loc+ SL"	INTEGER,
	"Pit+ SL"	INTEGER,
	"Stf+ KC"	TEXT,
	"Loc+ KC"	TEXT,
	"Pit+ KC"	TEXT,
	"Stf+ FC"	INTEGER,
	"Loc+ FC"	INTEGER,
	"Pit+ FC"	INTEGER,
	"Stf+ FS"	REAL,
	"Loc+ FS"	REAL,
	"Pit+ FS"	REAL,
	"Stuff+"	INTEGER,
	"Location+"	INTEGER,
	"Pitching+"	INTEGER,
	"Stf+ FO"	TEXT,
	"Loc+ FO"	TEXT,
	"Pit+ FO"	TEXT,
	PRIMARY KEY("teamIDfg")
);
"""

fangraphs_team_fielding_definition = """
CREATE TABLE "fangraphs_team_fielding_2025" (
	"teamIDfg"	INTEGER,
	"Season"	INTEGER,
	"Team"	TEXT,
	"G"	INTEGER,
	"GS"	INTEGER,
	"Inn"	REAL,
	"PO"	INTEGER,
	"A"	INTEGER,
	"E"	INTEGER,
	"FE"	INTEGER,
	"TE"	INTEGER,
	"DP"	INTEGER,
	"DPS"	INTEGER,
	"DPT"	INTEGER,
	"DPF"	INTEGER,
	"Scp"	INTEGER,
	"SB"	INTEGER,
	"CS"	INTEGER,
	"PB"	INTEGER,
	"WP"	INTEGER,
	"FP"	REAL,
	"TZ"	TEXT,
	"rSB"	INTEGER,
	"rGDP"	INTEGER,
	"rARM"	INTEGER,
	"rGFP"	INTEGER,
	"rPM"	INTEGER,
	"DRS"	INTEGER,
	"BIZ"	INTEGER,
	"Plays"	INTEGER,
	"RZR"	REAL,
	"OOZ"	INTEGER,
	"TZL"	TEXT,
	"FSR"	TEXT,
	"ARM"	TEXT,
	"DPR"	TEXT,
	"RngR"	TEXT,
	"ErrR"	TEXT,
	"UZR"	TEXT,
	"UZR/150"	TEXT,
	"CPP"	TEXT,
	"RPP"	TEXT,
	"Def"	REAL,
	"0%"	TEXT,
	"# 0%"	TEXT,
	"1-10%"	TEXT,
	"# 1-10%"	TEXT,
	"10-40%"	TEXT,
	"# 10-40%"	TEXT,
	"40-60%"	TEXT,
	"# 40-60%"	TEXT,
	"60-90%"	TEXT,
	"# 60-90%"	TEXT,
	"90-100%"	TEXT,
	"# 90-100%"	TEXT,
	"rSZ"	INTEGER,
	"rCERA"	INTEGER,
	"rTS"	INTEGER,
	"FRM"	REAL,
	"OAA"	INTEGER,
	"Range"	INTEGER,
	PRIMARY KEY("teamIDfg")
);
"""